Sofrware: Maya
Version: 2018
Exec: "C:/Program Files/Autodesk/Maya2018/bin/maya.exe"

Env:
    - name: MAYA_UI_LANGUAGE
      value: en_US
      mode: over
 
 
    - name: PYTHONPATH
      value: 'E:\pycharm_Code\python_file\Maya_file'
      mode: pre
     